{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "53e440ad",
   "metadata": {
    "vscode": {
     "languageId": "plaintext"
    }
   },
   "outputs": [],
   "source": [
    "{\n",
    " \"cells\": [\n",
    "  {\n",
    "   \"cell_type\": \"markdown\",\n",
    "   \"metadata\": {},\n",
    "   \"source\": [\n",
    "    \"# Marimo Notebook: NYC Taxi analysis\\n\",\n",
    "    \"\\n\",\n",
    "    \"Run the cells to connect to the DuckDB produced by the `taxi_pipeline`, inspect the data, and produce visualizations for the workshop questions.\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"import duckdb\\n\",\n",
    "    \"import pandas as pd\\n\",\n",
    "    \"import plotly.express as px\\n\",\n",
    "    \"import plotly.io as pio\\n\",\n",
    "    \"\\n\",\n",
    "    \"pio.renderers.default = 'notebook'\\n\",\n",
    "    \"\\n\",\n",
    "    \"# Path to the DuckDB file created by the pipeline\\n\",\n",
    "    \"duckdb_path = '/Users/carloskim/Developer/DE_zoomcamp/DE_zoomcamp/workshop_homework/taxi-pipeline/taxi_pipeline.duckdb'\\n\",\n",
    "    \"\\n\",\n",
    "    \"con = duckdb.connect(database=duckdb_path, read_only=True)\\n\",\n",
    "    \"print('Connected to', duckdb_path)\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"# Inspect tables and schema\\n\",\n",
    "    \"tables = con.execute(\\\"SELECT table_name FROM information_schema.tables WHERE table_schema='main'\\\").fetchdf()\\n\",\n",
    "    \"display(tables)\\n\",\n",
    "    \"\\n\",\n",
    "    \"# Pick table (adjust if your table name differs)\\n\",\n",
    "    \"table_name = 'trips'\\n\",\n",
    "    \"cols = con.execute(f\\\"PRAGMA table_info('{table_name}')\\\").fetchdf()\\n\",\n",
    "    \"display(cols[['name','type']])\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"# helper to infer likely column names; set manually if detection fails\\n\",\n",
    "    \"col_names = cols['name'].str.lower().tolist()\\n\",\n",
    "    \"def find_col(possible_names):\\n\",\n",
    "    \"    for n in possible_names:\\n\",\n",
    "    \"        for c in col_names:\\n\",\n",
    "    \"            if n in c:\\n\",\n",
    "    \"                return cols[cols['name'].str.lower() == c]['name'].iloc[0]\\n\",\n",
    "    \"    return None\\n\",\n",
    "    \"\\n\",\n",
    "    \"date_col = find_col(['pickup_datetime','tpep_pickup_datetime','pickup'])\\n\",\n",
    "    \"payment_col = find_col(['payment_type','payment'])\\n\",\n",
    "    \"tip_col = find_col(['tip_amount','tip'])\\n\",\n",
    "    \"print('Inferred columns -> date:', date_col, 'payment:', payment_col, 'tip:', tip_col)\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"# Question 1: dataset start and end date + daily trips time series\\n\",\n",
    "    \"if date_col is None:\\n\",\n",
    "    \"    print('Set date_col manually from schema above')\\n\",\n",
    "    \"else:\\n\",\n",
    "    \"    q = f\\\"\\\"\\\"\\n\",\n",
    "    \"    SELECT\\n\",\n",
    "    \"      MIN(CAST(\\\"{date_col}\\\" AS TIMESTAMP)) AS min_ts,\\n\",\n",
    "    \"      MAX(CAST(\\\"{date_col}\\\" AS TIMESTAMP)) AS max_ts,\\n\",\n",
    "    \"      COUNT(*) as total_rows\\n\",\n",
    "    \"    FROM \\\"{table_name}\\\"\\n\",\n",
    "    \"    \\\"\\\"\\\".format(date_col=date_col, table_name=table_name)\\n\",\n",
    "    \"    df_bounds = con.execute(q).fetchdf()\\n\",\n",
    "    \"    display(df_bounds)\\n\",\n",
    "    \"\\n\",\n",
    "    \"    q_counts = f\\\"\\\"\\\"\\n\",\n",
    "    \"    SELECT DATE_TRUNC('day', CAST(\\\"{date_col}\\\" AS TIMESTAMP)) AS day,\\n\",\n",
    "    \"           COUNT(*) AS cnt\\n\",\n",
    "    \"    FROM \\\"{table_name}\\\"\\n\",\n",
    "    \"    GROUP BY day\\n\",\n",
    "    \"    ORDER BY day\\n\",\n",
    "    \"    \\\"\\\"\\\".format(date_col=date_col, table_name=table_name)\\n\",\n",
    "    \"    df_counts = con.execute(q_counts).fetchdf()\\n\",\n",
    "    \"    df_counts['day'] = pd.to_datetime(df_counts['day'])\\n\",\n",
    "    \"    fig = px.line(df_counts, x='day', y='cnt', title='Trips per day')\\n\",\n",
    "    \"    fig.show()\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"# Question 2: proportion of trips paid with credit card\\n\",\n",
    "    \"if payment_col is None:\\n\",\n",
    "    \"    print('Set payment_col manually from schema above')\\n\",\n",
    "    \"else:\\n\",\n",
    "    \"    q_vals = f\\\"\\\"\\\"\\n\",\n",
    "    \"    SELECT \\\"{payment_col}\\\" as payment_val, COUNT(*) as cnt\\n\",\n",
    "    \"    FROM \\\"{table_name}\\\"\\n\",\n",
    "    \"    GROUP BY \\\"{payment_col}\\\"\\n\",\n",
    "    \"    ORDER BY cnt DESC\\n\",\n",
    "    \"    LIMIT 100\\n\",\n",
    "    \"    \\\"\\\"\\\".format(payment_col=payment_col, table_name=table_name)\\n\",\n",
    "    \"    df_payvals = con.execute(q_vals).fetchdf()\\n\",\n",
    "    \"    display(df_payvals)\\n\",\n",
    "    \"\\n\",\n",
    "    \"    if df_payvals['payment_val'].astype(str).str.lower().str.contains('credit').any():\\n\",\n",
    "    \"        q_credit = f\\\"\\\"\\\"\\n\",\n",
    "    \"        SELECT\\n\",\n",
    "    \"          100.0 * SUM(CASE WHEN LOWER(CAST(\\\"{payment_col}\\\" AS VARCHAR)) LIKE '%credit%' THEN 1 ELSE 0 END) / COUNT(*) AS credit_pct\\n\",\n",
    "    \"        FROM \\\"{table_name}\\\"\\n\",\n",
    "    \"        \\\"\\\"\\\".format(payment_col=payment_col, table_name=table_name)\\n\",\n",
    "    \"    else:\\n\",\n",
    "    \"        # assume numeric coding where 1 means credit (common)\\n\",\n",
    "    \"        q_credit = f\\\"\\\"\\\"\\n\",\n",
    "    \"        SELECT\\n\",\n",
    "    \"          100.0 * SUM(CASE WHEN CAST(\\\"{payment_col}\\\" AS BIGINT) = 1 THEN 1 ELSE 0 END) / COUNT(*) AS credit_pct\\n\",\n",
    "    \"        FROM \\\"{table_name}\\\"\\n\",\n",
    "    \"        \\\"\\\"\\\".format(payment_col=payment_col, table_name=table_name)\\n\",\n",
    "    \"\\n\",\n",
    "    \"    df_credit = con.execute(q_credit).fetchdf()\\n\",\n",
    "    \"    display(df_credit)\\n\",\n",
    "    \"    fig2 = px.bar(df_payvals, x='payment_val', y='cnt', title='Payment method distribution')\\n\",\n",
    "    \"    fig2.show()\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"# Question 3: total amount of money generated in tips\\n\",\n",
    "    \"if tip_col is None:\\n\",\n",
    "    \"    print('Set tip_col manually from schema above')\\n\",\n",
    "    \"else:\\n\",\n",
    "    \"    q_tips = f\\\"\\\"\\\"\\n\",\n",
    "    \"    SELECT SUM(CAST(\\\"{tip_col}\\\" AS DOUBLE)) as total_tips\\n\",\n",
    "    \"    FROM \\\"{table_name}\\\"\\n\",\n",
    "    \"    \\\"\\\"\\\".format(tip_col=tip_col, table_name=table_name)\\n\",\n",
    "    \"    df_tips = con.execute(q_tips).fetchdf()\\n\",\n",
    "    \"    display(df_tips)\\n\",\n",
    "    \"\\n\",\n",
    "    \"    q_tips_daily = f\\\"\\\"\\\"\\n\",\n",
    "    \"    SELECT DATE_TRUNC('day', CAST(\\\"{date_col}\\\" AS TIMESTAMP)) AS day,\\n\",\n",
    "    \"           SUM(CAST(\\\"{tip_col}\\\" AS DOUBLE)) AS total_tips\\n\",\n",
    "    \"    FROM \\\"{table_name}\\\"\\n\",\n",
    "    \"    GROUP BY day\\n\",\n",
    "    \"    ORDER BY day\\n\",\n",
    "    \"    \\\"\\\"\\\".format(date_col=date_col, tip_col=tip_col, table_name=table_name)\\n\",\n",
    "    \"    df_tips_daily = con.execute(q_tips_daily).fetchdf()\\n\",\n",
    "    \"    if not df_tips_daily.empty:\\n\",\n",
    "    \"        df_tips_daily['day'] = pd.to_datetime(df_tips_daily['day'])\\n\",\n",
    "    \"        fig3 = px.line(df_tips_daily, x='day', y='total_tips', title='Daily total tips')\\n\",\n",
    "    \"        fig3.show()\\n\"\n",
    "   ]\n",
    "  },\n",
    "  {\n",
    "   \"cell_type\": \"code\",\n",
    "   \"execution_count\": null,\n",
    "   \"metadata\": {},\n",
    "   \"outputs\": [],\n",
    "   \"source\": [\n",
    "    \"# Save summary and close\\n\",\n",
    "    \"summary = {}\\n\",\n",
    "    \"if 'df_bounds' in globals():\\n\",\n",
    "    \"    summary['start_date'] = pd.to_datetime(df_bounds['min_ts'].iloc[0]).strftime('%Y-%m-%d')\\n\",\n",
    "    \"    summary['end_date'] = pd.to_datetime(df_bounds['max_ts'].iloc[0]).strftime('%Y-%m-%d')\\n\",\n",
    "    \"if 'df_credit' in globals():\\n\",\n",
    "    \"    summary['credit_pct'] = float(df_credit.iloc[0,0])\\n\",\n",
    "    \"if 'df_tips' in globals():\\n\",\n",
    "    \"    summary['total_tips'] = float(df_tips['total_tips'].iloc[0])\\n\",\n",
    "    \"\\n\",\n",
    "    \"pd.Series(summary).to_csv('workshop_homework_summary.csv')\\n\",\n",
    "    \"print('Saved workshop_homework_summary.csv')\\n\",\n",
    "    \"con.close()\\n\"\n",
    "   ]\n",
    "  }\n",
    " ],\n",
    " \"metadata\": {\n",
    "  \"kernelspec\": {\n",
    "   \"display_name\": \"Python 3\",\n",
    "   \"language\": \"python\",\n",
    "   \"name\": \"python3\"\n",
    "  },\n",
    "  \"language_info\": {\n",
    "   \"name\": \"python\",\n",
    "   \"version\": \"3.11\"\n",
    "  }\n",
    " },\n",
    " \"nbformat\": 4,\n",
    " \"nbformat_minor\": 5\n",
    "}"
   ]
  }
 ],
 "metadata": {
  "language_info": {
   "name": "python"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
